name: quiz_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  http: ^0.13.5
  google_fonts: ^3.0.1
  page_transition: ^2.0.9
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.2
  lottie: ^1.4.3
  shimmer: ^2.0.0
  custom_refresh_indicator: ^2.0.1
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  fonts:
    - family: AgencyGothicCT
      fonts:
        - asset: assets/fonts/AgencyGothicCT.ttf

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svgs/
    - assets/fonts/AgencyGothicCT.ttf